[workspace]
members=[
    "sdk/logsdk",
    "sdk/pipeline2",
    "sdk/configuration",
    "framework/http",
    "demo/selfdemo",
    "demo/rocket",
    "demo/benchmark",
    "demo/cell",
    "base/cell-base-common",
    "base/core",
    "extensions/zkextension",
    "sdk/merkle_tree",
    "sdk/tree",
    "sdk/zktree_adapter"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
