[workspace]
members=[
    "sdk/logsdk",
    "sdk/pipeline",
    "demo/selfdemo",
    "demo/rocket",
    "demo/tokio",
    "base/cell-base-common",
    "base/core",
    "useless/hyper",
    "useless/demo"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
