[package]
name = "pipeline2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.5"
futures = "0.3.21"
tokio = "1.19.2"
async-recursion = "1.0.0"