[package]
name = "zkextension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merkle_tree = {path="../../sdk/merkle_tree"}
tree={path="../../sdk/tree"}
anyhow = "1.0.69"